print('Lê uma frase e diz coisas sobre ela')
frase = input('Escreva uma frase: ')
UP = frase.upper()
A = UP.count('A')
print('A letra "a" aparece {} vez(zes)'.format(A))
a = UP.find('A')
print('A letra "a" aparece primeiro na posição {}'.format(a))
i = UP.rfind('A')
print('A letra "a" aparece por ultimo na posição {}'.format(i))
